--CREATE DATABASE CLIENTEWPF
GO

USE [CLIENTEWPF]
GO

CREATE TABLE [CLIENTE](
	[CLI_CODIGO] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[CLI_CGC] [varchar](14) NULL,
	[CLI_NOME] [varchar](50) NULL,
	[CLI_ENDERECO] [int] NULL,
	[CLI_CELULAR] [varchar](11) NULL,
	[CLI_EMAIL] [varchar](50) NULL,
	[CLI_SEXO] [char](1) NULL CONSTRAINT CK_CLI_SEXO CHECK (CLI_SEXO IN ('M', 'F')),
	[CLI_NASCIMENTO] [date] NULL,
	[CLI_CADASTRO] [datetime2](7) NULL,
	[CLI_ATUALIZACAO] [datetime2](7) NULL,
	[CLI_ATIVO] [bit] NULL,
	[CLI_CODIGO_EXTERNO] [varchar](25) NULL
)

CREATE TABLE [ENDERECO](
	[END_CODIGO] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[END_CEP] [varchar] (8) NULL,
	[END_ENDERECO] [varchar] (70) NULL,
	[END_NUMERO] [varchar] (5) NULL,
	[END_BAIRRO] [varchar] (40) NULL,
	[END_CIDADE] [varchar] (50) NULL,
)